#!/bin/sh
while :
	do
		if [ -n "${MQTT_USER}" ]; then
			RXCMD=$(/usr/bin/mosquitto_sub -C 1 --will-topic ${TOPIC_LASTWILL} --will-payload offline -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_RX} -u ${MQTT_USER} -P ${MQTT_PASS})
		else
			RXCMD=$(/usr/bin/mosquitto_sub -C 1 --will-topic ${TOPIC_LASTWILL} --will-payload offline -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_RX})
		fi

		echo $RXCMD | nc 0 30006
	done
